//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDCS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LE Mapping.xlsx")]
        public string LEMapping {
            get {
                return ((string)(this["LEMapping"]));
            }
            set {
                this["LEMapping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item Mapping.xlsx")]
        public string ITEMMapping {
            get {
                return ((string)(this["ITEMMapping"]));
            }
            set {
                this["ITEMMapping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SDMatrix.xlsx")]
        public string SDMatrix {
            get {
                return ((string)(this["SDMatrix"]));
            }
            set {
                this["SDMatrix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300-InstallationSystemDisconnection")]
        public string DESC_INS {
            get {
                return ((string)(this["DESC_INS"]));
            }
            set {
                this["DESC_INS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300-WarrantySystemDisconnection")]
        public string DESC_WAR {
            get {
                return ((string)(this["DESC_WAR"]));
            }
            set {
                this["DESC_WAR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300-AppSystemDisconnection")]
        public string DESC_APPI {
            get {
                return ((string)(this["DESC_APPI"]));
            }
            set {
                this["DESC_APPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300-AdvAppSystemDisconnection")]
        public string DESC_APPII {
            get {
                return ((string)(this["DESC_APPII"]));
            }
            set {
                this["DESC_APPII"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300-VCPSystemDisconnection")]
        public string DESC_VCP {
            get {
                return ((string)(this["DESC_VCP"]));
            }
            set {
                this["DESC_VCP"] = value;
            }
        }
    }
}
